@startuml
title Диаграмма контекста

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(callCenterManager, "Менеджер кол-центра")
Person(outCallCenterManager, "Менеджер партнерского кол-центра")
Person(creditManager, "Кредитный менеджер")

System(callCenter, "Система кол-центра")
System(abs, "АБС")

System_Ext(emailSystem, "Электронная почта")
System_Ext(outCallCenter, "Система партнерского кол-центра")


creditManager --> abs : "Расчет актуальных ставок"
abs --> callCenter : "Передача актуальных ставок"
callCenterManager --> callCenter : "Просмотр ставок"

creditManager --> abs : "Получение файла актуальных ставок"
creditManager --> emailSystem : "Передача файла актуальных ставок"
emailSystem --> outCallCenterManager : "Получение файла актуальных ставок"
outCallCenterManager --> outCallCenter : "Сохранение актуальных ставок"


@enduml